export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const LOGOUT_OPTIMISTIC = "LOGOUT_OPTIMISTIC";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
